### ISSUE TITLE
Drop unnecessary parameters

### ISSUE THREAD

**Issue by tsalo** [nipreps/fmripost-rapidtide#7]
I'm trying to figure out which rapidtide parameters we can drop. @bbfrederick are there any that jump out to you?

As an fMRIPost workflow, it'll load input files automatically, so I think we can drop many of the parameters. Also, on a side note, it looks like there are 149 parameters, which is _a lot_ for a CLI.

I'm going to check off ones I think we can drop.

- [x] --denoising
- [x] --delaymapping
- [x] --CVR
- [x] --globalpreselect
- [x] --venousrefine
- [x] --nirs
- [x] ~~--brainmask MASK[:VALSPEC]~~
- [x] ~~--graymattermask MASK[:VALSPEC]~~
- [x] ~~--whitemattermask MASK[:VALSPEC]~~
- [x] ~~--datatstep TSTEP~~
- [x] ~~--datafreq FREQ~~
- [x] --noantialias
- [x] --invert
- [x] --interptype {univariate,cubic,quadratic}
- [x] --offsettime OFFSETTIME
- [ ] --autosync
- [ ] --filterband {None,vlf,lfo,resp,cardiac,hrv_ulf,hrv_vlf,hrv_lf,hrv_hf,hrv_vhf,lfo_legacy}
- [ ] --filterfreqs LOWERPASS UPPERPASS
- [ ] --filterstopfreqs LOWERSTOP UPPERSTOP
- [x] --filtertype {trapezoidal,brickwall,butterworth}
- [x] --butterorder ORDER
- [x] ~~--padseconds SECONDS~~ Just use the max (number of volumes minus 1)
- [x] --permutationmethod {shuffle,phaserandom}
- [ ] --numnull NREPS
- [x] --skipsighistfit
- [x] --windowfunc {hamming,hann,blackmanharris,None}
- [x] ~~--zeropadding PADVAL~~ Use the max (number of volumes minus 1)?
- [ ] --detrendorder ORDER
- [ ] --spatialfilt GAUSSSIGMA
- [x] --globalmean
- [x] --globalmaskmethod {mean,variance}
- [x] --globalmeaninclude MASK[:VALSPEC]
- [x] --globalmeanexclude MASK[:VALSPEC]
- [x] ~~--motionfile MOTFILE~~
- [x] ~~--motderiv~~
- [ ] --confoundfile CONFFILE
- [ ] --confoundpowers N
- [ ] --confoundderiv
- [x] --noconfoundorthogonalize
- [ ] --globalsignalmethod {sum,meanscale,pca,random}
- [ ] --globalpcacomponents VALUE
- [x] ~~--slicetimes FILE~~ Replace with `--ignore slicetiming`
- [ ] --numskip SKIP
- [ ] --numtozero NUMPOINTS
- [ ] --timerange START END
- [x] --nothresh
- [x] --oversampfac OVERSAMPFAC
- [x] --regressor FILE
- [x] --regressorfreq FREQ
- [x] --regressortstep TSTEP
- [x] --regressorstart START
- [ ] --corrweighting {None,phat,liang,eckart,regressor}
- [x] --corrtype {linear,circular}
- [x] --corrmaskthresh PCT
- [x] --corrmask MASK[:VALSPEC]
- [x] --similaritymetric {correlation,mutualinfo,hybrid}
- [x] --mutualinfosmoothingtime TAU
- [ ] --simcalcrange START END
- [ ] --fixdelay DELAYTIME
- [ ] --searchrange LAGMIN LAGMAX
- [ ] --sigmalimit SIGMALIMIT
- [ ] --bipolar
- [x] --nofitfilt
- [x] --peakfittype {gauss,fastgauss,quad,fastquad,COM,None}
- [x] --despecklepasses PASSES
- [x] --despecklethresh VAL
- [x] --refineprenorm {None,mean,var,std,invlag}
- [x] --refineweighting {None,NIRS,R,R2}
- [x] --passes PASSES
- [x] --refineinclude MASK[:VALSPEC]
- [x] --refineexclude MASK[:VALSPEC]
- [x] --norefinedespeckled
- [ ] --lagminthresh MIN
- [ ] --lagmaxthresh MAX
- [ ] --ampthresh AMP
- [ ] --sigmathresh SIGMA
- [x] --offsetinclude MASK[:VALSPEC]
- [x] --offsetexclude MASK[:VALSPEC]
- [x] --norefineoffset
- [x] --nopickleft
- [x] --pickleft
- [x] --pickleftthresh THRESH
- [x] --refineupperlag
- [x] --refinelowerlag
- [x] --refinetype {pca,ica,weighted_average,unweighted_average}
- [ ] --pcacomponents VALUE
- [ ] --convergencethresh THRESH
- [ ] --maxpasses MAXPASSES
- [x] --noglm
- [ ] --glmsourcefile FILE
- [x] --preservefiltering
- [ ] --glmderivs NDERIVS
- [ ] --outputlevel {min,less,normal,more,max}
- [x] --nolimitoutput
- [x] ~~--savelags~~
- [x] --histlen HISTLEN
- [x] ~~--saveintermediatemaps~~
- [x] --calccoherence
- [x] ~~--version~~
- [x] ~~--detailedversion~~
- [x] ~~--nprocs NPROCS~~
- [x] ~~--reservecpu~~
- [x] ~~--mklthreads MKLTHREADS~~
- [x] ~~--nonumba~~
- [x] ~~--noprogressbar~~
- [x] --checkpoint
- [x] --spcalculation
- [x] --dpoutput
- [x] ~~--cifti~~
- [x] ~~--simulate~~
- [x] ~~--displayplots~~
- [x] ~~--nosharedmem~~
- [x] ~~--memprofile~~
- [x] ~~--infotag tagkey tagvalue~~
- [ ] --territorymap MAP[:VALSPEC]
- [x] --psdfilter
- [x] --wiener
- [x] --corrbaselinespatialsigma SIGMA
- [x] --corrbaselinetemphpfcutoff FREQ
- [x] --spatialtolerance EPSILON
- [x] --echocancel
- [ ] --autorespdelete
- [x] --noisetimecourse FILENAME[:VALSPEC]
- [x] --noisefreq FREQ
- [x] --noisetstep TSTEP
- [x] --noisestart START
- [x] --noiseinvert
- [x] --acfix
- [x] --negativegradient
- [x] --cleanrefined
- [x] --dispersioncalc
- [x] ~~--tincludemask FILE~~
- [x] ~~--texcludemask FILE~~
- [x] ~~--debug~~
- [x] ~~--focaldebug~~
- [x] ~~--verbose~~
- [x] ~~--disabledockermemfix~~
- [x] ~~--alwaysmultiproc~~
- [x] --singleproc_confoundregress
- [x] --singleproc_getNullDist
- [x] --singleproc_calcsimilarity
- [x] --singleproc_peakeval
- [x] --singleproc_fitcorr
- [x] --singleproc_refine
- [x] --singleproc_makelaggedtcs
- [x] --singleproc_glm
- [x] --savecorrout
- [x] ~~--isatest~~

**Comment by bbfrederick** [comment]
Yes, most of the options are there for tuning weird types of experiments, or came from when I was designing the program - I've since picked default values that are generally pretty good.  Also, most of the tuning is only necessary when you want to do delay mapping in pathology - for straight up denoising, you don't need to and don't want to mess with most of the defaults.  It might be easier for me to specify which options to expose, rather than which to hide.

Github seems to let me check and uncheck boxes in your list, but I don't know if they stick or not.  I'll leave this comment, come back, and see if they have stuck.

**Comment by bbfrederick** [comment]
Ok, well it looks like they stick.  So for straight up denoising, this is the maximum number of things you'd support (honestly, at least half of them can probably be locked down as well).  But then there's a philosophical question - what is fmripost-rapidtide FOR?  If it's to do denoising, which I'd argue is a necessary step if you are going to do any sort of resting state analysis, then these options are good.  If we also want to allow people to do delay calculations and other more interesting hemodynamic measures, we might want to enable more options.  But if people do that, I think probably they should do the whole rapidtide installation and just use it directly.  Thoughts?

**Comment by tsalo** [comment]
Just to be clear, that is not a top-down mission statement for this tool. It is just how I personally envision it. I'm definitely open to modifying the plan.

**Comment by tsalo** [comment]
The current list of 33 parameters seems much more manageable. I think we can still drop `--confoundfile`, `--territorymap`, and `--glmsourcefile` though. I'm hopeful that we can identify and load those internally.
